import java.awt.Color;
import java.awt.Font;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;


public class BDL extends JPanel 
{
//JLabels	
	private JLabel lblBosal;
	private JLabel lblBDL;
	private JLabel lblCustomer;
	private JLabel lblPlatform;
	private JLabel lblType;
	private JLabel lblName;
	private JLabel lblVolume;
	private JLabel lblPower;
	private JLabel lblEngine;
	private JLabel lblBosalPartNum;
	private JLabel lblCustomerPartNum;
	private JLabel lblIMDS;
	private JLabel lblDescription;
	private JLabel lblSilencer;
	private JLabel lblVolume2;
	private JLabel lblLength;
	private JLabel lblSection;
	private JLabel lblIssuedBy;
	private JLabel lblPage;
	private JLabel lblREV;
	private JLabel lblRelDate;
	private JLabel lblREVDate;
	private JLabel lblProduction;
	private JLabel lblRelPlant1;
	private JLabel lblRelPlant2;
	private JLabel lblRelSupplier;
	private JLabel lblBOSAL;
	private JLabel lblCUSTOMER;
	
//JTextFields
	private JTextField txtCustomer;
	private JTextField txtPlatform;
	private JTextField txtType;
	private JTextField txtName;
	private JTextField txtVolume;
	private JTextField txtPower;
	private JTextField txtEngine;
	private JTextField txtBosalPartNum;
	private JTextField txtCustomerPartNum;
	private JTextField txtIMDS;
	private JTextField txtDescription;
	private JTextField txtSilencer;
	private JTextField txtVolume2;
	private JTextField txtLength;
	private JTextField txtSection;
	private JTextField txtIssuedBy;
	private JTextField txtPage;
	private JTextField txtREV;
	private JTextField txtRelDate;
	private JTextField txtREVDate;
	private JTextField txtProduction;
	private JTextField txtRelPlant1;
	private JTextField txtRelPlant2;
	private JTextField txtRelSupplier;
	
	JPanel contentPane;
	
	public BDL(JPanel pnlMain) 	
	{	
		setBackground(new Color(105, 105, 105));
		contentPane = pnlMain;
		setOpaque(true);
		setVisible(true);
						
	//Images
		ImageIcon bosal = new ImageIcon(getClass().getResource("/images/bosal.jpg"));
		lblBosal = new JLabel(bosal);
		lblBosal.setBounds(10, 11, 194, 56);
		
	//JLabels
		lblBDL = new JLabel("Breakdown List Manager");
		lblBDL.setFont(new Font("EucrosiaUPC", Font.BOLD, 64));
		lblBDL.setForeground(Color.BLACK);
		lblBDL.setBounds(214, 26, 482, 40);
		lblCustomer = new JLabel("Customer:");
		lblCustomer.setBackground(new Color(150, 150, 150));
		lblCustomer.setOpaque(true);
		lblCustomer.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblCustomer.setForeground(Color.BLACK);
		lblCustomer.setBounds(30, 82, 128, 92);
		lblPlatform = new JLabel("Platform:");
		lblPlatform.setBackground(new Color(150, 150, 150));
		lblPlatform.setOpaque(true);
		lblPlatform.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblPlatform.setForeground(Color.BLACK);
		lblPlatform.setBounds(30, 174, 128, 22);
		lblType = new JLabel("Type:");
		lblType.setBackground(new Color(150, 150, 150));
		lblType.setOpaque(true);
		lblType.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblType.setForeground(Color.BLACK);
		lblType.setBounds(76, 194, 82, 27);
		lblName = new JLabel("Name:");
		lblName.setBackground(new Color(150, 150, 150));
		lblName.setOpaque(true);
		lblName.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblName.setForeground(Color.BLACK);
		lblName.setBounds(76, 217, 82, 16);
		lblVolume = new JLabel("Volume (L):");
		lblVolume.setBackground(new Color(150, 150, 150));
		lblVolume.setOpaque(true);
		lblVolume.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblVolume.setForeground(Color.BLACK);
		lblVolume.setBounds(76, 232, 82, 27);
		lblPower = new JLabel("Power (kW):");
		lblPower.setBackground(new Color(150, 150, 150));
		lblPower.setOpaque(true);
		lblPower.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblPower.setForeground(Color.BLACK);
		lblPower.setBounds(75, 259, 83, 27);
		lblEngine = new JLabel("Engine");
		lblEngine.setBackground(new Color(150, 150, 150));
		lblEngine.setOpaque(true);
		lblEngine.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblEngine.setForeground(Color.BLACK);
		lblEngine.setBounds(30, 194, 47, 92);
		lblBosalPartNum = new JLabel("BOSAL PART NR");
		lblBosalPartNum.setBackground(new Color(150, 150, 150));
		lblBosalPartNum.setOpaque(true);
		lblBosalPartNum.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblBosalPartNum.setForeground(Color.BLACK);
		lblBosalPartNum.setBounds(125, 437, 98, 22);
		lblCustomerPartNum = new JLabel("CUSTOMER PART NR");
		lblCustomerPartNum.setBackground(new Color(150, 150, 150));
		lblCustomerPartNum.setOpaque(true);
		lblCustomerPartNum.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblCustomerPartNum.setForeground(Color.BLACK);
		lblCustomerPartNum.setBounds(483, 488, 123, 27);
		lblIMDS = new JLabel("IMDS");
		lblIMDS.setBackground(new Color(150, 150, 150));
		lblIMDS.setOpaque(true);
		lblIMDS.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblIMDS.setForeground(Color.BLACK);
		lblIMDS.setBounds(375, 488, 98, 27);
		lblDescription = new JLabel("DESCRIPTION");
		lblDescription.setBackground(new Color(150, 150, 150));
		lblDescription.setOpaque(true);
		lblDescription.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblDescription.setForeground(Color.BLACK);
		lblDescription.setBounds(260, 413, 123, 40);
		lblSilencer = new JLabel("Silencer");
		lblSilencer.setBackground(new Color(150, 150, 150));
		lblSilencer.setOpaque(true);
		lblSilencer.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblSilencer.setForeground(Color.BLACK);
		lblSilencer.setBounds(93, 377, 91, 16);
		lblVolume2 = new JLabel("Volume (L):");
		lblVolume2.setBackground(new Color(150, 150, 150));
		lblVolume2.setOpaque(true);
		lblVolume2.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblVolume2.setForeground(Color.BLACK);
		lblVolume2.setBounds(79, 333, 94, 33);
		lblLength = new JLabel("Length:");
		lblLength.setBackground(new Color(150, 150, 150));
		lblLength.setOpaque(true);
		lblLength.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblLength.setForeground(Color.BLACK);
		lblLength.setBounds(561, 321, 77, 25);
		lblSection = new JLabel("Section:");
		lblSection.setBackground(new Color(150, 150, 150));
		lblSection.setOpaque(true);
		lblSection.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblSection.setForeground(Color.BLACK);
		lblSection.setBounds(242, 464, 123, 40);
		lblIssuedBy = new JLabel("Issued By:");
		lblIssuedBy.setBackground(new Color(150, 150, 150));
		lblIssuedBy.setOpaque(true);
		lblIssuedBy.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblIssuedBy.setForeground(Color.BLACK);
		lblIssuedBy.setBounds(76, 471, 123, 27);
		lblPage = new JLabel("Page:");
		lblPage.setBackground(new Color(150, 150, 150));
		lblPage.setOpaque(true);
		lblPage.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblPage.setForeground(Color.BLACK);
		lblPage.setBounds(560, 357, 98, 31);
		lblREV = new JLabel("REV:");
		lblREV.setBackground(new Color(150, 150, 150));
		lblREV.setOpaque(true);
		lblREV.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblREV.setForeground(Color.BLACK);
		lblREV.setBounds(242, 336, 106, 27);
		lblRelDate = new JLabel("Rel Date:");
		lblRelDate.setBackground(new Color(150, 150, 150));
		lblRelDate.setOpaque(true);
		lblRelDate.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblRelDate.setForeground(Color.BLACK);
		lblRelDate.setBounds(351, 375, 123, 27);
		lblREVDate = new JLabel("REV Date:");
		lblREVDate.setBackground(new Color(150, 150, 150));
		lblREVDate.setOpaque(true);
		lblREVDate.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblREVDate.setForeground(Color.BLACK);
		lblREVDate.setBounds(437, 340, 98, 19);
		lblProduction = new JLabel("Production:");
		lblProduction.setBackground(new Color(150, 150, 150));
		lblProduction.setOpaque(true);
		lblProduction.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblProduction.setForeground(Color.BLACK);
		lblProduction.setBounds(105, 404, 98, 22);
		lblRelPlant1 = new JLabel("Rel Plant 1:");
		lblRelPlant1.setBackground(new Color(150, 150, 150));
		lblRelPlant1.setOpaque(true);
		lblRelPlant1.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblRelPlant1.setForeground(Color.BLACK);
		lblRelPlant1.setBounds(133, 515, 116, 27);
		lblRelPlant2 = new JLabel("Rel Plant 2:");
		lblRelPlant2.setBackground(new Color(150, 150, 150));
		lblRelPlant2.setOpaque(true);
		lblRelPlant2.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblRelPlant2.setForeground(Color.BLACK);
		lblRelPlant2.setBounds(306, 538, 77, 19);
		lblRelSupplier = new JLabel("Rel Supplier:");
		lblRelSupplier.setBackground(new Color(150, 150, 150));
		lblRelSupplier.setOpaque(true);
		lblRelSupplier.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblRelSupplier.setForeground(Color.BLACK);
		lblRelSupplier.setBounds(250, 375, 91, 27);
		lblBOSAL = new JLabel("BOSAL");
		lblBOSAL.setBackground(new Color(150, 150, 150));
		lblBOSAL.setOpaque(true);
		lblBOSAL.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblBOSAL.setForeground(Color.BLACK);
		lblBOSAL.setBounds(483, 437, 92, 22);
		lblCUSTOMER = new JLabel("CUSTOMER");
		lblCUSTOMER.setBackground(new Color(150, 150, 150));
		lblCUSTOMER.setOpaque(true);
		lblCUSTOMER.setFont(new Font("Tahoma", Font.BOLD, 14));
		lblCUSTOMER.setForeground(Color.BLACK);
		lblCUSTOMER.setBounds(476, 397, 116, 29);
		
	//JTextFields
		txtCustomer = new JTextField();
		txtCustomer.setForeground(Color.BLACK);
		txtCustomer.setBounds(803, 492, 111, 22);
		txtPlatform = new JTextField();
		txtPlatform.setForeground(Color.BLACK);
		txtPlatform.setBounds(816, 454, 98, 27);
		txtType = new JTextField();
		txtType.setForeground(Color.BLACK);
		txtType.setBounds(656, 475, 116, 22);
		txtName = new JTextField();
		txtName.setForeground(Color.BLACK);
		txtName.setBounds(670, 437, 116, 27);
		txtVolume = new JTextField();
		txtVolume.setForeground(Color.BLACK);
		txtVolume.setBounds(836, 326, 98, 27);
		txtPower = new JTextField();
		txtPower.setForeground(Color.BLACK);
		txtPower.setBounds(836, 278, 98, 22);
		txtEngine = new JTextField();
		txtEngine.setForeground(Color.BLACK);
		txtEngine.setBounds(836, 239, 98, 16);
		txtBosalPartNum = new JTextField();
		txtBosalPartNum.setForeground(Color.BLACK);
		txtBosalPartNum.setBounds(826, 209, 98, 14);
		txtCustomerPartNum = new JTextField();
		txtCustomerPartNum.setForeground(Color.BLACK);
		txtCustomerPartNum.setBounds(826, 176, 98, 22);
		txtIMDS = new JTextField();
		txtIMDS.setForeground(Color.BLACK);
		txtIMDS.setBounds(816, 135, 98, 22);
		txtDescription = new JTextField();
		txtDescription.setForeground(Color.BLACK);
		txtDescription.setBounds(806, 103, 98, 22);
		txtSilencer = new JTextField();
		txtSilencer.setForeground(Color.BLACK);
		txtSilencer.setBounds(806, 71, 98, 16);
		txtVolume2 = new JTextField();
		txtVolume2.setForeground(Color.BLACK);
		txtVolume2.setBounds(816, 427, 100, 16);
		txtLength = new JTextField();
		txtLength.setForeground(Color.BLACK);
		txtLength.setBounds(705, 401, 86, 25);
		txtSection = new JTextField();
		txtSection.setForeground(Color.BLACK);
		txtSection.setBounds(695, 374, 98, 16);
		txtIssuedBy = new JTextField();
		txtIssuedBy.setForeground(Color.BLACK);
		txtIssuedBy.setBounds(696, 290, 97, 27);
		txtPage = new JTextField();
		txtPage.setForeground(Color.BLACK);
		txtPage.setBounds(695, 326, 98, 27);
		txtREV = new JTextField();
		txtREV.setForeground(Color.BLACK);
		txtREV.setBounds(857, 364, 77, 19);
		txtRelDate = new JTextField();
		txtRelDate.setForeground(Color.BLACK);
		txtRelDate.setBounds(836, 394, 98, 22);
		txtREVDate = new JTextField();
		txtREVDate.setForeground(Color.BLACK);
		txtREVDate.setBounds(693, 203, 100, 27);
		txtProduction = new JTextField();
		txtProduction.setForeground(Color.BLACK);
		txtProduction.setBounds(693, 157, 98, 27);
		txtRelPlant1 = new JTextField();
		txtRelPlant1.setForeground(Color.BLACK);
		txtRelPlant1.setBounds(691, 114, 100, 27);
		txtRelPlant2 = new JTextField();
		txtRelPlant2.setForeground(Color.BLACK);
		txtRelPlant2.setBounds(681, 77, 100, 27);
		txtRelSupplier = new JTextField();
		txtRelSupplier.setForeground(Color.BLACK);
		txtRelSupplier.setBounds(703, 247, 100, 27);
		
		setupPanel();
	}
	private void setupPanel() 
	{
		setLayout(null);
		add(lblBosal);
		add(lblBDL);
		add(lblCustomer);
		add(lblPlatform);
		add(lblType);
		add(lblName);
		add(lblVolume);
		add(lblPower);
		add(lblEngine);
		add(lblBosalPartNum);
		add(lblCustomerPartNum);
		add(lblIMDS);
		add(lblDescription);
		add(lblSilencer);
		add(lblVolume2);
		add(lblLength);
		add(lblSection);
		add(lblIssuedBy);
		add(lblPage);
		add(lblREV);
		add(lblRelDate);
		add(lblREVDate);
		add(lblProduction);
		add(lblRelPlant1);
		add(lblRelPlant2);
		add(lblRelSupplier);
		add(lblBOSAL);
		add(lblCUSTOMER);
		add(txtCustomer);
		add(txtPlatform);
		add(txtType);
		add(txtName);
		add(txtVolume);
		add(txtPower);
		add(txtEngine);
		add(txtBosalPartNum);
		add(txtCustomerPartNum);
		add(txtIMDS);
		add(txtDescription);
		add(txtSilencer);
		add(txtVolume2);
		add(txtLength);
		add(txtSection);
		add(txtIssuedBy);
		add(txtPage);
		add(txtREV);
		add(txtRelDate);
		add(txtREVDate);
		add(txtProduction);
		add(txtRelPlant1);
		add(txtRelPlant2);
		add(txtRelSupplier);
		
	}
}